ReactionMechanismGenerator/RMG-website

- rmgweb/media/expandingMenu.js
- rmgweb/rmg/forms.py
- rmgweb/rmg/models.py
- rmgweb/rmg/templates/input.html
- rmgweb/rmg/templates/inputResult.html
- rmgweb/rmg/urls.py
- rmgweb/urls.py
Major changes:
* Updated additional options to match available options
* Added section for species constraints
* Updated pdep section
* Added QMTP section
* Added sensitivity analysis option for reactor systems
* Updated descriptions, added some links to documentation
* Slightly modified CSS
The form works for loading and writing input files for a variety of cases that I've tested. There could still be specific cases that I missed which break, so please try it out. There is an associated pull request for RMG-Py.
I also tried to add an option to set the interpolation scheme for pdep to False, which is a option according to the documentation. I haven't been able to get it to work yet, so it is not in this pull request. Does interpolation=False currently work properly, and does anyone …
> Updates to Create Input File Page

- rmgweb/rmg/__init__.py
- rmgweb/rmg/models.py
- rmgweb/rmg/templates/input.html
- rmgweb/rmg/views.py
This PR mainly fixes issues caused by the relocation of scripts to the /scripts folder.
There is also one commit that fixes a typo on the Create Input File page.
The model comparison tool also requires a fix to the script in RMG-Py (pointing to the new ReactionModel class), which will be in a separate PR.
> Fixes to RMG Tools

- rmgweb/rmg/models.py
In combination with 
https://github.com/ReactionMechanismGenerator/RMG-Py/pull/483
this PR removes the need for subprocess calls for diffmodels, merge models, and populate reactions.
> Remove subprocess calls to RMG-Py functions

- rmgweb/database/templates/groupDraw.html
- rmgweb/rmg/templates/rmg.html
- rmgweb/rmg/urls.py
- rmgweb/templates/base.html
- rmgweb/urls.py
After #109 this pull request does two things that I propose but people might want to discuss:
1. move the URL of things currently at  /simulate/  to be at /tools/. I think this is a more descriptive name
2. move the group_draw feature from the top level home page to the /tools/ page. This removes it from the sidebar menu, adds it to the tools page menu, and changes its url from /group_draw to /tools/group_draw. I feel it's not one of the most important things for new users and our landing page is overly complicated.
> Move group draw to /tools/ page

- rmgweb/database/tools.py
- rmgweb/rmg/models.py
- rmgweb/rmg/templates/input.html
Following change in RMG-Py to output family reactions with molecule objects instead of species objects, perform conversion in RMG-website. Fixes #111. 
Also add option for filter reactions to input file form.
> Fix Kinetics Search and add filter reactions to Create Input File

- rmgweb/main/templatetags/render_thermo.py
The notation was wrong for a long time, it should be standard entropy instead of entropy of formation. One can easily test hydrogen, if it's entropy of formation, the value should be zero.
This PR tries to correct the notation, to avoid confusing the users.
> The entropy in thermo estimation should be standard entropy

- rmgweb/database/templates/moleculeSearch.html
- rmgweb/main/views.py
In the backend, many error notifications received are issues of identifier parsing. Most of them are due to the user providing an invalid identifier, however, in the current website, there is no way to distinguish a bad identifier or a correct identifier but cannot be read by RMG (for example, when containing elements like metals). Improved error handling is implemented.
1. when an unknown element encountered, it will figure out if the element is valid or not supported by RMG.
2. when a bad atomtype encountered, it will figure out whether it is actually good but not recognizable by RMG.
> Improve error handling when getting invalid identifiers

- rmgweb/database/views.py
In the previous website, some results return links to the reactions in the reverse direction. This PR allows all reaction links in the result list directed to the correct reactions (instead of the reversed reactions for some of the entries).
> BugFix: return links to rxns with correct direction in kinetic search

- rmgweb/main/views.py
Since NCI resolver can return some weird structure. It is better to provide this information as well. NCI cannot parse carbon monoxide correctly, so we add it known_names.
> Further improve error handling of adjacency list generation

- rmgweb/secretsettings.py.example
- rmgweb/settings.py
This email address is used to sending emails from the website. It is relevant to password reset
> Overwrite DEFAULT_FROM_EMAIL in the settings

- rmgweb/database/views.py
The previous BugFix b2fffe171e746afda8078830c3a5d9785347c8d2 returns the correct link, but makes the listing reaction in the wrong direction. This commit aims to fix this issue.
> BugFix: return the correct direction reaction when searching kinetics

- rmgweb/database/templates/kineticsSearch.html
RMG was done twice in the past two days. By looking at the access log and error log, it is clear that both events had the same cause:  A user requested a kinetic search of the molecule below (with generate_resonance=True).
This query takes very long (far exceeding our timeout limit). And what makes it worse, the user just impatiently relaunched the request multiple times in a very short period of time (within a few minutes). Then, all daemon processes were occupied, and all new requests were blocked.
In general, it is possible that some people will run into those time-consuming searches (or other functions). In that scenario, the connection between clients and the server will be terminated after some time, while the job on the server is still running, which blocks further requests. …
> Add loading image and recommendations in kinetic search

- rmgweb/database/tools.py
This is an update related to RMG-Py and RMG-database:
https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2025
https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2074
https://github.com/ReactionMechanismGenerator/RMG-database/pull/387
In the latest version RMG backend, a new RMG metal database was added to allow thermo estimations based on different metallic surfaces. In order to correctly load the metal database, the `load_surface()` function is called whenever reloading the RMG database (`load()`) / RMG thermo database (`load('thermo')`); `'surface'` is added as an optional section argument for `load` for potential future development.
> Load metal database

- rmgweb/main/templates/resources.html
This update allows users to find the links to the 2021 workshop and relevant resources.
> Add 2021 workshop to resources

- rmgweb/database/views.py
Previously, only reverse rates of Arrhenius (and its children) or KineticsData class are generated. That causes many entries shown as `There are no kinetics for this entry` (e.g., results of C <=> [CH3] + [H]). The update allows showing reverse rates for Chebyshev and other types of kinetics supported by `generate_reverse_rate_coefficient`.
Worth to note, the accuracy/validity of `generate_reverse_rate_coefficient` is not checked (which is beyond the scope of this change I think).
There is an example to show the differences:
Current RMG website:
https://rmg.mit.edu/database/kinetics/reaction/reactant1=1%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%20%7B5,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A5%20H%20u0%20p0 …
> Show reverse rates whenever available in kinetics data page

- rmgweb/main/templatetags/render_kinetics.py
Aims to solve #215.
In some cases,  a unit is written as 1/XXX (e.g., 1/s), which cannot be handled by the current RMG-website. This commit aims to solve that problem.
> BugFix: handling unit of '1/XXX'

- environment.yml
- rmgweb/database/tools.py
Updates RMG-website to accommodate recent upgrade to OpenBabel3. 
The [recent update to OpenBabel3 in RMG-Py](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2088/files) changed the environment file; additionally there is an inconsistency with how `pybel` is imported between the two versions of OpenBabel. This PR seeks to address those inconsistencies.
> Compatibility with OpenBabel3

- rmgweb/database/templates/thermoData.html
- rmgweb/database/views.py
- rmgweb/main/templatetags/render_thermo.py
Implements feature suggested in #214.
When group additivity thermo estimations are generated, typically a `comment` is added that informs what library and/or groups were used to generate that estimate. This comment is then displayed by the website. This implementation implements a new feature that automatically links to the relevant library or groups in the reported thermo comment whenever they are detected.
Sample implementation:
[(1) Species in original feature request](https://rmg.mit.edu:888/database/thermo/molecule/1%20O%20u0%20p2%20c0%20%7B3,S%7D%20%7B5,S%7D%0A2%20O%20u0%20p2%20c0%20%7B3,D%7D%0A3%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B2,D%7D%20%7B4,S%7D%0A4%20X%20u0%20p0%20c0%20%7B3,S%7D%0A5%20X%20u0%20p0%20c0%20%7B1,S%7D%0A)
[(2) Example of handling missing …
> Add hyperlinks to group additivity thermo estimates

- rmgweb/database/views.py
This PR seeks to fix a bug that causes individual family kinetics pages to load extremely slowly.
Requests to all kinetics sites are handled in the `kinetics` function. The code attempts to generate a KineticsDatabase object depending on the subsection of kinetics (e.g. `groups`, `training`, `rules`, if present) and family name (if present).
If no valid KineticsDatabase object is found (such as when the subsection is not able to be parsed `get_kinetics_database` e.g. does not fall under `groups` or `training`, etc) then the website attempts to render the "list view" [See https://rmg.mit.edu/database/kinetics/families/ for the "list view" of all families]. It is possible to specify the _family name_ as the subsection, which results in loading the list view only for that family.
In the …
> Fix to slow individual kinetics family entry pages

- environment.yml
- rmgweb/database/views.py
One of the packages (chemprop_solvation) has a bug and needs to be updated in order for the SoluteML solvation tool to work properly on RMG-website. This PR will fix it.
Please run:
`conda env update -f environment.yml`
`pip install git+https://github.com/bp-kelley/descriptastorus`
Then the Solute parameter search tool on https://rmg.mit.edu/database/solvation/soluteSearch/ with `Machine Learning Prediction (SoluteML)` as an estimation method will work.
Test this by entering the following input:
`[H][H] C(CBr)O c1ccccc1 C(C)(=O)O C1=CC=CC2=CC=CC=C12 lllllll Mg`
Choose `Machine Learning Prediction (SoluteML)` as an estimation method and `water` as a solvent.
You should get a table showing results below:
> Update `chemprop_solvation` with a newer version >=0.0.3 to fix a bug with SoluteML

- rmgweb/main/templatetags/render_thermo.py
When searching for species involving Wilhoit thermo, the website will crash upon rendering the thermo view, citing an `AttributeError`.
Search "CCC" in the Molecule Search --> Search Thermochemistry leads to the `AttributeError`. [Example here](https://rmg.mit.edu/database/thermo/molecule/multiplicity%202%0A1%20%20C%20%20u0%20p0%20c0%20%7B2,S%7D%20%7B5,S%7D%20%7B6,S%7D%20%7B7,S%7D%0A2%20%20C%20%20u1%20p0%20c0%20%7B1,S%7D%20%7B3,S%7D%20%7B4,S%7D%0A3%20%20Cl%20u0%20p3%20c0%20%7B2,S%7D%0A4%20%20C%20%20u0%20p0%20c0%20%7B2,S%7D%20%7B8,S%7D%20%7B9,S%7D%20%7B10,S%7D%0A5%20%20H%20%20u0%20p0%20c0%20%7B1,S%7D%0A6%20%20H%20%20u0%20p0%20c0%20%7B1,S%7D%0A7%20%20H%20%20u0%20p0%20c0%20%7B1,S%7D%0A8%20%20H%20%20u0%20p0%20c0%20%7B4,S%7D%0A9%20%20H%20%20u0%20p0%20c0%20%7B4,S%7D%0A10%20H%20%20u0%20p0%20c0%20 …
> Fix typo in processing Wilhoit thermo that leads to AttributeError

- rmgweb/database/templates/solvationSoluteSearch.html
- rmgweb/database/views.py
**Motivation**
Currently, the [Solute and Solvation LSER Search](https://rmg.mit.edu/database/solvation/soluteSearch/) using the group contribution method only displays the name of the groups found for the input molecules as shown below.
This is inconvenient since the user has to search for each group if they want to know the group value.
**Changes Made**
This commit now adds the hyperlink to each group found for the group contribution method as shown below. Clicking each group will direct the user to the page containing the detailed information of the group.
Similar changes have been made for the solute parameter search using the RMG-database. Clicking the comment will direct the user to the page containing the matched library entry.
> Add hyperlink link to the groups for the solvation group contribution method

- environment.yml
The version 1.2 of the solprop package version is currently broken out-of-the-box. This commit just changes the version number in the `environment.yml` file to 1.1 (which is known to be stable) as a fix is prepared.
> Downgrade solprop from >=1.2 to =1.1

- environment.yml
Previously, solprop version 1.2 had a critical error so a previous PR (#242) was introduced to downgrade it. This PR undoes the downgrade as the latest version of solprop is now stable.
> Update environment.yml to latest version of solprop

- README.md
- environment.yml
Be consistent with the latest RMG-Py (May 9 2023) at commit f4d7e9
> Update RMG website environmental file

- rmgweb/database/tools.py
See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2605. Group additivity methods for kinetics were removed from RMG-Py.  As a result, many kinetic searches using RMG website fail with ValueError.
It is not clear whether these will return, and I expect there will probably be some discussion about this - but that might take some time. This PR is a temporary (and possibly permanent, if we decide to just permanently retire group additivity methods) workaround that removes any mentions to kinetic group additivity methods from the RMG-website codebase.
See difference between kinetic searches 
*RMG-dev*: https://rmg.mit.edu:888/database/kinetics/reaction/reactant1=1%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%20%7B5,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p …
> Fix kinetic search due to removal of group additivity methods for rates from RMG-Py

- rmgweb/templates/base.html
The RMG website used Google Universal Analytics to track and understand user behavior. The universal analytics stopped working on 2023/07/01. I just tried to migrate services to Google Analytics 4. This PR adds the necessary tag to enable GA4.
@jonwzheng I suggest we test this on the dev first, and then eventually merge it onto the website.
> Update tracker from Google UA to GA4

- rmgweb/templates/base.html
See #269. UA is deprecated since last year and will completely stop working on July 1st (within a week!) so we need to update this asap. Tested this on the dev branch and it appears to work properly.
> Update tracker from Google UA to Google GA4 for main branch

- environment.yml
- rmgweb/database/tools.py
- rmgweb/main/views.py
This PR:
* removes groups from drawing graphs due to an unexplained path issue with `neato`, possibly due to package versions.
* prevents `KineticsModel` data (namely, from recently added Chung TS parameters) from showing up in kinetics search, which also yields crashes for a large variety of species.
> Temporary fixes to website crash issues

- rmgweb/database/tools.py
Addresses #294.
Previous commit (https://github.com/ReactionMechanismGenerator/RMG-website/commit/caed55017e63bfea33e39a8e301f3a16ee00dcb0) was aimed at removing website crashes which occurred due library-sourced data with `KineticsModel` kinetics, which do not have any reaction data and therefore cause a crash. 
That removed from search _any_ kinetics which were instances of `KineticsModel`. However, this had the unintended effect of also removing data that are instances of subclasses of `KineticsModel` which _are_ valid and should be included in the kinetics search.
This PR just changes the relevant change to check for class equivalence and not just `isinstance()` which also checks for subclass.
(Tested locally; this restores the kinetics search.)
> HOTFIX: fix Reaction Libraries from being omitted from kinetics search
